### ISSUE TITLE
READMEの記述とGPL3ライセンスの矛盾

### ISSUE THREAD

**Issue by takaki** [YuriCat/FujiGokoroUECda#11]
READMEに
> ただし、大会出場以外での利用は要相談でお願い致します。

とありますがGPL-3と矛盾した内容に思えますがどういう意図でしょうか？

**Comment by YuriCat** [comment]
ご連絡ありがとうございます。確認致します。

**Comment by YuriCat** [comment]
ご指摘の通りかと思われますので、README.mdの当該記述は削除致しました。
ご指摘まことにありがとうございました。
